### PR TITLE
Update code to run on python3

### PR DESCRIPTION
**Pull request by am0z**
Signed-off-by: Andrey Mozgunov <am0z@ya.ru>

### CODE REVIEW

**Comment by ronbeltran** [comment]
Thanks @am0z , I have it initially developed on Python2.

**Comment by ronbeltran** [comment]
Apparently this PR introduced a bug: (I used python3.4 on ubuntu 14.04)

```
$ nosetests --verbose
test_all_bounces (tests.test_bounce_email.BounceEmailTest) ... ok
test_all_non_bounces (tests.test_bounce_email.BounceEmailTest) ... ok
test_bounce_from_auto_responder (tests.test_bounce_email.BounceEmailTest) ... ok
test_bounce_type_hard_fail (tests.test_bounce_email.BounceEmailTest) ... ok
test_bounce_type_soft_fail (tests.test_bounce_email.BounceEmailTest) ... ok
test_does_not_fail_if_subject_is_none (tests.test_bounce_email.BounceEmailTest) ... ok
test_mail_methods_fallback (tests.test_bounce_email.BounceEmailTest) ... ok
test_malformed_bounce (tests.test_bounce_email.BounceEmailTest) ... ok
test_multipart (tests.test_bounce_email.BounceEmailTest) ... ok
test_original_message_with_bounced_gmail (tests.test_bounce_email.BounceEmailTest) ... ok
test_original_message_with_inline_original_message (tests.test_bounce_email.BounceEmailTest) ... ok
test_original_message_with_multipart_mails (tests.test_bounce_email.BounceEmailTest) ... ok
test_original_message_with_multipart_mails_without_to_field (tests.test_bounce_email.BounceEmailTest) ... ok
test_original_message_with_subject (tests.test_bounce_email.BounceEmailTest) ... ok
test_original_message_without_inline_original_message (tests.test_bounce_email.BounceEmailTest) ... ok
test_permanent_failure (tests.test_bounce_email.BounceEmailTest) ... ok
test_rota_dnsbl (tests.test_bounce_email.BounceEmailTest) ... FAIL
test_set_5_0_status (tests.test_bounce_email.BounceEmailTest) ... ok
test_unknown_code (tests.test_bounce_email.BounceEmailTest) ... ok
test_unrouteable_mail_domain (tests.test_bounce_email.BounceEmailTest) ... ok
test_user_unknown (tests.test_bounce_email.BounceEmailTest) ... ok

======================================================================
FAIL: test_rota_dnsbl (tests.test_bounce_email.BounceEmailTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbeltran/Github/ronbeltran/bounce_email/tests/test_bounce_email.py", line 64, in test_rota_dnsbl
    self.assertEqual(bounce.code, '5.7.1', 'Bounce code should be 5.7.1')
AssertionError: '5.0.0' != '5.7.1'
- 5.0.0
+ 5.7.1
 : Bounce code should be 5.7.1

----------------------------------------------------------------------
Ran 21 tests in 0.501s

FAILED (failures=1)
 
```

**Comment by am0z** [comment]
Weird thing is i've run test on python 27, 34, 35, and 36 with no errors. Anyway, I'll be setting up some CI service with tox and multple python versions in comming few days.

PS: what was exact python3.4 version on your ubuntu? Mine was 3.4.6.

**Comment by ronbeltran** [comment]
Hey @am0z, I've tested on Python version 3.4.3 on Ubuntu 14.04. Havent tested yet on other versions.
The error is not consistently reproduced.  Running succeeding `nosetest --verbose` yields pass and failed tests.

```
$ python
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by am0z** [comment]
Hey, it's been awhile!

Finally got to the bottom of this.

First, I've set up CI on CircleCI with multiple python version. Then I discovered that the tests were failing with exact message as above on multiple versions but not always.

Long story short:
```
for k, v in status_patterns.items():
    match = search(v)
    if match:
        return k
```

The order of dict.items() is not guaranteed so it was matching on another `status_patterns` sometimes.

The test expects `tests/bounces/tt_bounce_06.txt` to match against `5.7.1` pattern, but the file also matches on `5.0.0`.  So whichever comes first--order not guaranteed--that pattern get to `bounce.code`.

Proposal:
* use OrderedDict for `status_patterns`
* expect multiple bounce code in test

**Pull request merged**
